language: python

sudo: false

matrix:
  include:
   - env: TOXENV=pep8
     python: 3.6

install: 
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - pip install tox
  - pip install pytest
  - python setup.py develop

script:
  - tox
  - python manage.py test tests/test_docs.py --nocontext
