language: python

sudo: false

matrix:
  include:
    - os: linux
      env:
        - TOXENV=pep8
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      python: 3.6

install: 
  - pip install tox
  - pip install pytest
  - python setup.py develop

script:
  - tox
  - pytest tests/test_docs.py tests/test_window.py
